backend:
  name: git-gateway
  branch: OMS-105/FooterContentCMS

media_folder: static/img
public_folder: /img

collections:
  - name: "englishPerks"
    label: "en/Perk"
    folder: "src/entities/en/perks"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Perk name", name: "title", widget: "string"}
      - {label: "Text", name: "text", widget: "string"}

  - name: "norwegianPerks"
    label: "no/Perk"
    folder: "src/entities/no/perks"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Perk name", name: "title", widget: "string"}
      - {label: "Text", name: "text", widget: "string"}

  - name: "norwegian_employees"
    label: "no/Employee"
    folder: "src/entities/no/employees"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Job title", name: "jobTitle", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
      - label: "Job type"
        name: "jobType"
        widget: "select"
        options:
        - {label: "Front-end", value: "frontEnd"}
        - {label: "Back-end", value: "backEnd"}
        - {label: "Management", value: "management"}
        - {label: "Operations", value: "operations"}
        - {label: "Summer intern", value: "summerIntern"}

  - name: "english_employees"
    label: "en/Employee"
    folder: "src/entities/en/employees"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Job title", name: "jobTitle", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
      - label: "Job type"
        name: "jobType"
        widget: "select"
        options:
        - {label: "Front-end", value: "frontEnd"}
        - {label: "Back-end", value: "backEnd"}
        - {label: "Management", value: "management"}
        - {label: "Operations", value: "operations"}
        - {label: "Summer intern", value: "summerIntern"}

  - name: "norwegian_featureCard"
    label: "no/FeatureCard"
    folder: "src/entities/no/featureCards"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Språk", name: "language", widget: "hidden", default: "no"}
      - {label: "Bilde", name: "image", widget: "image"}
      - {label: "Tittel", name: "title", widget: "string"}
      - {label: "Beskrivelse", name: "description", widget: "text"}
      - {label: "Features", name: "features", widget: "list"}

  - name: "english_featureCard"
    label: "en/FeatureCard"
    folder: "src/entities/en/featureCards"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Language", name: "language", widget: "hidden", default: "en"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Features", name: "features", widget: "list"}

  - name: "norwegian_products"
    label: "no/Product"
    folder: "src/pages/no/products"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blogPost"}
      - {label: "Language", name: "language", widget: "hidden", default: "no"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - label: "Referenced English post"
        name: "english_post"
        widget: "relation"
        collection: "english_products"
        searchFields: ["title"]
        valueField: "slug"
        displayFields: ["title"]

  - name: "english_products"
    label: "en/Product"
    folder: "src/pages/en/products"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blogPost"}
      - {label: "Language", name: "language", widget: "hidden", default: "en"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - label: "Referenced Norwegian post"
        name: "norwegian_post"
        widget: "relation"
        collection: "norwegian_products"
        searchFields: ["title"]
        valueField: "slug"
        displayFields: ["title"]
  
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/no/index.md"
        name: "norwegian_index_page"
        label: "no/Homepage"
        fields:
          - {label: "Welcome Image", name: "topImage", widget: "image"}
          - label: "Featured Content"
            name: "featuredContent"
            widget: "object"
            fields:
              - {label: "Featured Case Header", name: "header", widget: "string"}
              - {label: "Featured Image", name: "image", widget: "image"}
              - {label: "Featured Text", name: "text", widget: "text"}
          - label: "Customization"
            name: "customization"
            widget: "object"
            fields:
              - {label: "Header", name: "header", widget: "string"}
              - {label: "Cards", name: "cards", widget: "list", fields: [
                  {label: "Header", name: "header", widget: "string"},
                  {label: "Image", name: "image", widget: "image"},
                  {label: "Description", name: "description", widget: "text"},
                  {label: "Features", name: "features", widget: "list"},
                ]}
          - label: "Configuration logos"
            name: "configurationLogos"
            widget: "list"
            fields:
              - {label: "Logo", name: "logo", widget: "image"}
          - label: "Solutions Content"
            name: "solutionsContent"
            widget: "object"
            fields:
              - {label: "Header", name: "header", widget: "string"}
              - {label: "First Card", name: "firstCard", widget: "object", fields: [
                  {label: "Image", name: "image", widget: "image"},
                  {label: "Header", name: "header", widget: "string"},
                  {label: "Text", name: "text", widget: "text"},
                ]}
              - {label: "Second Card", name: "secondCard", widget: "object", fields: [
                  {label: "Image", name: "image", widget: "image"},
                  {label: "Header", name: "header", widget: "string"},
                  {label: "Text", name: "text", widget: "text"},
                ]}
          - label: "Customer logos"
            name: "customerLogos"
            widget: "list"
            fields:
              - {label: "Logo", name: "logo", widget: "image"}

      - file: "src/pages/en/index.md"
        name: "english_index_page"
        label: "en/Homepage"
        fields:
          - {label: "Welcome Image", name: "topImage", widget: "image"}
          - label: "Featured Content"
            name: "featuredContent"
            widget: "object"
            fields:
              - {label: "Featured Case Header", name: "header", widget: "string"}
              - {label: "Featured Image", name: "image", widget: "image"}
              - {label: "Featured Text", name: "text", widget: "text"}
          - label: "Customization"
            name: "customization"
            widget: "object"
            fields:
              - {label: "Header", name: "header", widget: "string"}
              - {label: "Cards", name: "cards", widget: "list", fields: [
                  {label: "Header", name: "header", widget: "string"},
                  {label: "Image", name: "image", widget: "image"},
                  {label: "Description", name: "description", widget: "text"},
                  {label: "Features", name: "features", widget: "list"},
                ]}
          - label: "Configuration logos"
            name: "configurationLogos"
            widget: "list"
            fields:
              - {label: "Logo", name: "logo", widget: "image"}
          - label: "Solutions Content"
            name: "solutionsContent"
            widget: "object"
            fields:
              - {label: "Header", name: "header", widget: "string"}
              - {label: "First Card", name: "firstCard", widget: "object", fields: [
                  {label: "Image", name: "image", widget: "image"},
                  {label: "Header", name: "header", widget: "string"},
                  {label: "Text", name: "text", widget: "text"},
                ]}
              - {label: "Second Card", name: "secondCard", widget: "object", fields: [
                  {label: "Image", name: "image", widget: "image"},
                  {label: "Header", name: "header", widget: "string"},
                  {label: "Text", name: "text", widget: "text"},
                ]}
          - label: "Customer logos"
            name: "customerLogos"
            widget: "list"
            fields:
              - {label: "Logo", name: "logo", widget: "image"}

      - file: "src/pages/no/about/index.md"
        name: "norwegian_about_page"
        label: "no/About page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "aboutPage"}
          - {label: "First header", name: "title", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Text", name: "text", widget: "text"}
          - {label: "Second header", name: "header", widget: "string"}

      - file: "src/pages/en/about/index.md"
        name: "english_about_page"
        label: "en/About page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "aboutPage"}
          - {label: "First header", name: "title", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Text", name: "text", widget: "text"}
          - {label: "Second header", name: "header", widget: "string"}

      - file: "src/pages/no/career/index.md"
        name: "norwegian_career_page"
        label: "no/Career page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "careerPage"}
          - {label: "First header", name: "title", widget: "string"}
          - {label: "First image", name: "image1", widget: "image"}
          - {label: "First text", name: "text1", widget: "text"}
          - {label: "Second header", name: "header", widget: "string"}
          - {label: "Second image", name: "image2", widget: "image"}
          - {label: "Second text", name: "text2", widget: "text"}
          - {label: "First sub-header", name: "subHeader1", widget: "string"}
          - {label: "Second sub-header", name: "subHeader2", widget: "string"}

      - file: "src/pages/en/career/index.md"
        name: "english_career_page"
        label: "en/Career page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "careerPage"}
          - {label: "First header", name: "title", widget: "string"}
          - {label: "First image", name: "image1", widget: "image"}
          - {label: "First text", name: "text1", widget: "text"}
          - {label: "Second header", name: "header", widget: "string"}
          - {label: "Second image", name: "image2", widget: "image"}
          - {label: "Second text", name: "text2", widget: "text"}
          - {label: "First sub-header", name: "subHeader1", widget: "string"}
          - {label: "Second sub-header", name: "subHeader2", widget: "string"}

      - file: "src/pages/no/products/index.md"
        name: "norwegian_products_page"
        label: "no/Products page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "productsPage"}
          - {label: "Intro", name: "intro", widget: "object", fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "Links", name: "links", widget: "list", fields: [
                {label: "Title", name: "title", widget: "string"},
                {label: "Text", name: "text", widget: "string"},
                {label: "Image", name: "image", widget: "image"},
              ]},
            ]}
          - {label: "Investor Portals", name: "investorPortal", widget: "object", fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "Description", name: "description", widget: "text"},
              {label: "Features", name: "features", widget: "list", fields: [
                {label: "Title", name: "title", widget: "string"},
                {label: "Description", name: "description", widget: "text"},
                {label: "Image", name: "image", widget: "image"},
              ]},
            ]}
          - {label: "Products", name: "products", widget: "list", fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "Image", name: "image", widget: "image"},
              {label: "Description", name: "description", widget: "text"},
            ]}


      - file: "src/pages/en/products/index.md"
        name: "english_products_page"
        label: "en/Products page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "productsPage"}
          - {label: "Intro", name: "intro", widget: "object", fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "Links", name: "links", widget: "list", fields: [
                {label: "Title", name: "title", widget: "string"},
                {label: "Text", name: "text", widget: "string"},
                {label: "Image", name: "image", widget: "image"},
              ]},
            ]}
          - {label: "Investor Portals", name: "investorPortal", widget: "object", fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "Description", name: "description", widget: "text"},
              {label: "Features", name: "features", widget: "list", fields: [
                {label: "Title", name: "title", widget: "string"},
                {label: "Description", name: "description", widget: "text"},
                {label: "Image", name: "image", widget: "image"},
              ]},
            ]}
          - {label: "Products", name: "products", widget: "list", fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "Image", name: "image", widget: "image"},
              {label: "Description", name: "description", widget: "text"},
            ]}

      - file: "src/pages/footer/index.md"
        name: "footer"
        label: "Footer"
        fields: 
          - {label: "Group websites", name: "groupWebsites", widget: "object", fields: [
              {label: "Oslo Børs VPS", name: "osloBorsVPS", widget: "list", fields: [
                {label: "Title", name: "title", widget: "string"},
                {label: "URL", name: "url", widget: "string"},
              ]},
            ]}